### ISSUE TITLE
We REALLY need to get the test suite green again

### ISSUE THREAD

**Issue by troygrosfield** [tschellenbach/Django-facebook#537]
There are two main errors that seem to be the guilty culprit:

The first one can be seen executing the test below. This error accounts for about **70% of the test suite failures** (16 of these errors / 23 total failures):
```
ERROR: test_utf8 (django_facebook.tests.UserConnectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/tests.py", line 626, in test_utf8
    action, user = connect_user(self.request, facebook_graph=graph)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 93, in connect_user
    remove_old_connections=force_registration)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 255, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 318, in _update_user
    current_facebook_id = get_user_attribute(user, profile, 'facebook_id')
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/utils.py", line 109, in get_user_attribute
    'user or profile didnt have attribute %s' % attribute)
AttributeError: user or profile didnt have attribute facebook_id
```
The common error is:
```
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 93, in connect_user
    remove_old_connections=force_registration)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 255, in _register_user
    new_user = _update_user(new_user, facebook)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/connect.py", line 318, in _update_user
    current_facebook_id = get_user_attribute(user, profile, 'facebook_id')
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/utils.py", line 109, in get_user_attribute
    'user or profile didnt have attribute %s' % attribute)
AttributeError: user or profile didnt have attribute facebook_id
```
Which can be seen throughout the test suite runs.

The second one is:

```
======================================================================
ERROR: test_connect_redirect_authenticated (django_facebook.tests.ConnectViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/tests.py", line 230, in test_connect_redirect_authenticated
    response = self.client.get(accepted_url, follow=True)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/decorators.py", line 99, in wrapped_view
    response = self.authenticate(self.fn, request, *args, **kwargs)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/decorators.py", line 180, in authenticate
    fn, request, graph=graph, *args, **kwargs)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/decorators.py", line 138, in execute_view
    result = view_func(*args, **kwargs)
  File "/home/travis/build/tschellenbach/Django-facebook/django_facebook/views.py", line 41, in connect
    raise ValueError(message)
ValueError: Please specify a Facebook app id and ensure the context processor is enabled
```
If we can get these two fixed, the majority of the test suite will be fixed.

**Comment by detinho** [comment]
Hi,
I forked the repo to try work on this issue [1]. The first thing I saw was that travis was stoping the build on the pep8 verification. After fixing that I've ran the test suite, but got far more erros / failures than listed here. Should we continue on this issue or open a new one?

[1] https://github.com/detinho/Django-facebook/tree/gogreen

**Comment by troygrosfield** [comment]
@detinho, we can continue it from this issue. It would be great to get all test passing again.  I just ran out of time working on it.

**Comment by tschellenbach** [comment]
thanks for helping out.

**Comment by detinho** [comment]
It's green now! The problem with the missing facebook_id field was a hardcoded `facebookprofile` access on the user instance. As django model creates an attribute based on the class name (if not specified by the user of course), the profile was always `None`.
I changed that behavior, by looking for the profile attribute that matches the class on `AUTH_PROFILE_MODULE`.
I've made some other minor changes on the tests too.

**Comment by troygrosfield** [comment]
Thanks again for your contribution @detinho!  That PR was a very big help!

**Comment by troygrosfield** [comment]
It's a thing of beauty!

<img width="898" alt="screen shot 2016-03-18 at 5 00 07 pm" src="https://cloud.githubusercontent.com/assets/1551551/13894191/fd0b3f04-ed2a-11e5-86af-fab7d95acca3.png">

**Comment by detinho** [comment]
\o/ Nice! Glad to help!

**Comment by tschellenbach** [comment]
this is awesome, love open source :)
